### ISSUE TITLE
"python modules can`t be found" error

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/cloud#140]
My paddle cloud job need some thirdparty python modules which can`t be found in paddle cloud worker. So i upload some thirdparty libs to data center and set PYTHONPATH in my entry script. It truly  fixed some import errors. But is there an easy solution ? 
For example: Let user upload docker image, builded by user,  to datacenter. And we can config  which docker image worker should use when submit job.

**Comment by Yancey1989** [comment]
@wanghaoshuang , Thanks for your suggestion, submit the job with custom runtime Docker image is very useful, `paddlecloud` has already supported this feature with specifying the parameter `paddlecloud submit  ... -image {your image}`. But in Baidu internal registry Server,  we need a registry secret, so that PaddleCloud would pull the runtime Docker image, so I think we also implement the following features:

- `paddlecloud` supports adding a registry secret

```bash
paddlecloud add secret registry_secret 
  -name ${custom secret name}
  -username ${registry username}
  -password ${registry password}
  -registry_server ${your registry server domain}
```
- Add a parameter `paddlecloud submit -registry_secret ${custom secret name} ...` to pull the docker Image from secret registry server.


- Add usage doc to explain how to build the customer runtime Docker image.
