### ISSUE TITLE
Investigating autoscale trainer job on PaddleCloud

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#379]
### Background
  A Paddle training job contains several trainer instances(Kubernetes Job), several parameter server instances((Kubernetes ReplicaSet) and a master process(only fault-tolerant mode, Kubernetes ReplicaSet). We hope PaddleCloud has the ability which can autoscaling the count of trainer instances. This issue would like to discuss how to implement this feature.

### HPA on Kubernetes
  With [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)(HPA), Kubernetes is able to scale the number of Pod automatically, users will use HPA as:
```bash
kubectl autoscale rc foo --min=2 --max=5 --cpu-percent=80
 ```
Which:
- `min` is the low limit for the number of pods.
- `max` is the high limit for the number of pods.
- `--cpu-percent` is the target average CPU utilization.
  
#### Fetch metrics
From Kubernetes Doc:
> The Horizontal Pod Autoscaler is implemented as a control loop, with a period controlled by the controller manager’s --horizontal-pod-autoscaler-sync-period flag (with a default value of 30 seconds).

- Heapster access
  [heapster]https://github.com/kubernetes/heapster enables Container Cluster Monitoring and Performance Analysis, and use InfluxDB as the backend storage.

- [REST client access](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics)

### Problem
From now on, the HPA only support ReplicaSet and Deployment, but the trainer is a Job in Kubernets.

### Possible solutions
- Fix HPA to support Job Resource
The Job in Kubernetes supports `scale`, so maybe we can extend HPA to support Job, and I think it's a better way.

- Custom server to scale Job instance
We can also develop another simple service to check the metrics for a sync period and call `scale` API to scale the Trainer instance.

**Comment by typhoonzero** [comment]
Need to let HPA to scale jobs.

**Comment by putcn** [comment]
Can we convert trainers to the type of Deployment or ReplicaSet instead?

**Comment by helinwang** [comment]
## Scaling Metrics

### Background

We can scale jobs (jobs in the general sense, not the k8s Job) by:

1. the Horizontal Pod Autoscaling (HPA), or
1. manually by a custom server.

Both approaches requires scaling metrics.

HPA support per Pod CPU and memory metrics out-of-the-box. Custom metrics can be collected from each Pod.

The CPU and memory usage is probably **not** a good indicator for scaling trainers, since each trainer's memory and CPU usage is almost constant since the training process is a periodic iterative calculation process.

### Inference Job Scaling Metrics

We need to scale inference jobs based on the load for each Pod that runs the inference server. Query Per Second (QPS) is a good indicator.

### Training Job Scaling Metrics

The auto-scaling for training jobs should be based on the "cluster resource usage" (i.e., number of GPUs that can be elastically scaled, the resource-requirement-pressure of other job types such as inference job).

### Kubernetes Support

Currently HPA does not support Kubernetes Job that the trainer users, and the scaling API [changed since 1.6](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics). Perhaps currently the best thing to do is to scale manually by a custom server.

**Comment by helinwang** [comment]
After some research, maybe one good way of abstracting the training job is to create a custom resource (Job and Deployment are resources) and a custom controller.
The custom controller knows how many GPU nodes are available, so it can dynamically scale all training jobs accordingly.

**Comment by helinwang** [comment]
Design Doc: Horizontal Autoscaling: https://github.com/PaddlePaddle/cloud/pull/380
